-- MySQL Script generated by MySQL Workbench
-- Mon Feb 22 17:41:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema v0mgbm8nfthxqwz1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `v0mgbm8nfthxqwz1` ;

-- -----------------------------------------------------
-- Schema v0mgbm8nfthxqwz1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `v0mgbm8nfthxqwz1` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `v0mgbm8nfthxqwz1` ;

-- -----------------------------------------------------
-- Table `v0mgbm8nfthxqwz1`.`chats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `v0mgbm8nfthxqwz1`.`chats` ;

CREATE TABLE IF NOT EXISTS `v0mgbm8nfthxqwz1`.`chats` (
  `chat_id` INT(11) NOT NULL AUTO_INCREMENT,
  `chat_uid` VARCHAR(255) NULL DEFAULT NULL,
  `chat_name` VARCHAR(255) NULL DEFAULT NULL,
  `chat_type` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`chat_id`),
  INDEX `chat_uid_index` (`chat_uid` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1090
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `v0mgbm8nfthxqwz1`.`chats_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `v0mgbm8nfthxqwz1`.`chats_users` ;

CREATE TABLE IF NOT EXISTS `v0mgbm8nfthxqwz1`.`chats_users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `chat_uid` VARCHAR(255) NOT NULL DEFAULT '',
  `u_id` VARCHAR(255) NOT NULL,
  `archiveChat` TINYINT(1) NULL DEFAULT '0',
  `delete_chat` TINYINT(4) NOT NULL DEFAULT '0',
  `favorite` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_chatuid_idx` (`chat_uid` ASC) VISIBLE,
  INDEX `fk_uid_idx` (`u_id` ASC) VISIBLE,
  CONSTRAINT `fk_chatuid`
    FOREIGN KEY (`chat_uid`)
    REFERENCES `v0mgbm8nfthxqwz1`.`chats` (`chat_uid`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_uid`
    FOREIGN KEY (`u_id`)
    REFERENCES `v0mgbm8nfthxqwz1`.`usrs` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 75
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `v0mgbm8nfthxqwz1`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `v0mgbm8nfthxqwz1`.`messages` ;

CREATE TABLE IF NOT EXISTS `v0mgbm8nfthxqwz1`.`messages` (
  `message_id` INT(11) NOT NULL AUTO_INCREMENT,
  `chat_uid` VARCHAR(255) NOT NULL DEFAULT '',
  `u_id` VARCHAR(255) NOT NULL,
  `message` TEXT NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `time` TIMESTAMP NULL DEFAULT NULL,
  `delete_message` TINYINT(1) NULL DEFAULT NULL,
  `delete_message_to` TINYINT(1) NOT NULL DEFAULT '0',
  `unread_messages` TINYINT(4) NOT NULL DEFAULT '0',
  `favorite` TINYINT(4) NOT NULL DEFAULT '0',
  `is_image` TINYINT(1) NOT NULL DEFAULT '0',
  `is_file` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`message_id`),
  INDEX `fk_chatuid_idx` (`chat_uid` ASC) VISIBLE,
  INDEX `fk_uid_idx` (`u_id` ASC) VISIBLE,
  CONSTRAINT `fk_chats_chatuid`
    FOREIGN KEY (`chat_uid`)
    REFERENCES `v0mgbm8nfthxqwz1`.`chats` (`chat_uid`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usrs_uid`
    FOREIGN KEY (`u_id`)
    REFERENCES `v0mgbm8nfthxqwz1`.`usrs` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7703
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `v0mgbm8nfthxqwz1`.`sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `v0mgbm8nfthxqwz1`.`sessions` ;

CREATE TABLE IF NOT EXISTS `v0mgbm8nfthxqwz1`.`sessions` (
  `session_id` VARCHAR(128) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `expires` INT(11) UNSIGNED NOT NULL,
  `data` MEDIUMTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`session_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `v0mgbm8nfthxqwz1`.`usrs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `v0mgbm8nfthxqwz1`.`usrs` ;

CREATE TABLE IF NOT EXISTS `v0mgbm8nfthxqwz1`.`usrs` (
  `id` INT(100) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `usrname` VARCHAR(255) NOT NULL DEFAULT '',
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `verified` INT(255) NULL DEFAULT NULL,
  `last_update` TIMESTAMP NULL DEFAULT NULL,
  `created` DATE NULL DEFAULT NULL,
  `u_id` VARCHAR(255) NULL DEFAULT NULL,
  `random` VARCHAR(255) NULL DEFAULT NULL,
  `u_type` INT(255) NOT NULL,
  `Country` TEXT NULL DEFAULT NULL,
  `website` TEXT NULL DEFAULT NULL,
  `Avatar` VARCHAR(255) NULL DEFAULT NULL,
  `city` TEXT NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `public` VARCHAR(255) NULL DEFAULT NULL,
  `about` TEXT NULL DEFAULT NULL,
  `pphoto` VARCHAR(255) NULL DEFAULT NULL,
  `theme` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `uid_index` (`u_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 74
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
